replicaCount: 1

image:
  repository: docker.io/ramazziniadedev/private
  pullPolicy: IfNotPresent  
  tag: ""

imagePullSecrets: 
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:  
  create: true  
  annotations: {}  
  name: "store-microservice"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

resources:  
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}